---
version: '3'

services:
  ajv-validator:
    image: onsdigital/eq-questionnaire-validator:${TAG}-ajv
    networks:
      - eq-schema
    ports:
      - 5002:5002
    healthcheck:
      test: "curl localhost:5002/status"
      interval: 5s
      timeout: 5s
      retries: 20

  py-validator:
    image: onsdigital/eq-questionnaire-validator:${TAG}
    networks:
      - eq-schema
    environment:
      AJV_HOST: ajv-validator
    ports:
      - 5001:5000
    depends_on:
      ajv-validator:
        condition: service_healthy
networks:
  eq-schema:
    driver: bridge
