name: PR

on: 
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install jsonnet
        run: |
          mkdir jsonnet
          curl -o jsonnet.tar.gz -L https://github.com/google/jsonnet/releases/download/v0.14.0/jsonnet-bin-v0.14.0-linux.tar.gz
          tar -xzf jsonnet.tar.gz -C jsonnet
          echo "::add-path::jsonnet"
      - name: Lint jsonnet
        run: make lint-jsonnet
      - name: Build schemas
        run: make build-schemas
      - name: Archive schema artifacts
        uses: actions/upload-artifact@v1
        with:
          name: schemas
          path: schemas
  test-translation-templates:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Download built schemas
        uses: actions/download-artifact@v1
        with:
          name: schemas
      - name: Install pipenv
        run: pip install pipenv==2018.11.26
      - name: Cache virtualenv
        id: cache-virtualenv
        uses: actions/cache@v1
        with:
            path: ~/.local/share/virtualenvs/
            key: ${{ runner.os }}-virtualenvs-${{ hashFiles('Pipfile.lock') }}
      - name: Install virtual environment
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: pipenv install --dev
      - name: Test translation templates
        run: make test-translation-templates
  test-schemas:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download built schemas
        uses: actions/download-artifact@v1
        with:
          name: schemas
      - name: Pull and run validator
        run: make run-validator
      - name: Test schemas
        run: make test-schemas