name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install jsonnet
        run: |
          mkdir jsonnet
          curl -o jsonnet.tar.gz -L https://github.com/google/jsonnet/releases/download/v0.14.0/jsonnet-bin-v0.14.0-linux.tar.gz
          tar -xzf jsonnet.tar.gz -C jsonnet
          echo "::add-path::jsonnet"
      - name: Install pipenv --dev
        run: pip install pipenv==2018.11.26
      - run: |
          echo "::set-env name=PYTHON_VERSION::$(python -c 'import platform; print(platform.python_version())')"
      - name: Cache virtualenv
        id: cache-virtualenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs/
          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-virtualenvs-${{ hashFiles('Pipfile.lock') }}
      - name: Install virtual environment
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: pipenv install --dev
      - name: Lint jsonnet
        run: make lint
      - name: Build schemas
        run: make build
      - name: Archive schema artifacts
        uses: actions/upload-artifact@v1
        with:
          name: schemas
          path: schemas
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download schemas
        uses: actions/download-artifact@v1
        with:
          name: schemas
      - name: Zip artifacts
        run: zip -r schemas.zip schemas
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: schemas.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  notify-runner:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Get schema version
        uses: actions/checkout@v2
      - run: |
          GITHUB_REF=`echo ${{ github.ref }}`
          TAG_CLEAN="${GITHUB_REF/refs\/tags\//}"
          echo "::set-env name=TAG::$TAG_CLEAN"
      - name: Notify Runner
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: "${{ secrets.REPO_ACCESS_TOKEN }}"
          repository: "ONSdigital/eq-questionnaire-runner"
          event-type: "schemas_release"
          client-payload: '{"tag": "${{ env.TAG }}"}'